/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminGeradorConfigsRouteImport } from './routes/admin.gerador-configs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGeradorConfigsRoute = AdminGeradorConfigsRouteImport.update({
  id: '/admin/gerador-configs',
  path: '/admin/gerador-configs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/gerador-configs': typeof AdminGeradorConfigsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/gerador-configs': typeof AdminGeradorConfigsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/gerador-configs': typeof AdminGeradorConfigsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/gerador-configs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/gerador-configs'
  id: '__root__' | '/' | '/admin/gerador-configs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminGeradorConfigsRoute: typeof AdminGeradorConfigsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gerador-configs': {
      id: '/admin/gerador-configs'
      path: '/admin/gerador-configs'
      fullPath: '/admin/gerador-configs'
      preLoaderRoute: typeof AdminGeradorConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminGeradorConfigsRoute: AdminGeradorConfigsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
